### ISSUE TITLE
Create Asotin IMW Program

### ISSUE THREAD

**Issue by philipbaileynar** [NorthArrowResearch/riverscapes-programs#2]
@MattReimer please create a new data warehouse program called "Aostin IMW". The IMW stands for "intensively monitored watershed". Initial (more to come) project types:

- Topo Toolbar
- CAD Export
- Hydro Model
- Fish habitat
- GCD
- GUT
- Riverscapes Context
- VBET

## Comments

- This is billable work for Anabranch. I am working on the GUT and GCD project definitions.
- This request is time sensitive. I should be ready to put projects in by the end of Thursday.
- Note this is a good example of where we will need:
    - program only editable by select users (Anabranch & ELR)
    - Read only warehouse visible to the public without sign-in.

**Comment by MattReimer** [comment]
moved to new repo.
https://github.com/Riverscapes/RiverscapesXML/issues/2
